name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install mypy
      run: |
        pip install --upgrade pip
        pip install mypy
        mypy --version

    - name: Run mypy
      run: mypy -p logitechd --python-version ${{ matrix.python }}
